### PR TITLE
Gateway API / Cert-manager Crds

### PR DESCRIPTION
**Pull request by luminosita**
Minor update to CRDs

cert-manager: depricated flag "installCRDs"
gateway API CRDs: gatewayclass was not accepted after CIlium deployment during Talos bootstrap. This fixed that issue. I guess you opted for Cilium reinstall once Talos bootstrap finishes.

All the best,

### CODE REVIEW

**Comment by Mdleal** [comment]
I spent 2 days trying to figure this out and as this is my first time using kube and terra it was a great learning experience.

**Comment by Mdleal** [comment]
I was not able to get this working the commit suggested but was able to load the CRDs with the following.

  extraManifests:
    - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml

**Comment by vehagn** [comment]
Thank you for the corrections @luminositas!

Do you mind rebasing your commits to resolve the conflicts? I can do this if it's OK with you. I'd also appreciate it if you could prefix your commit messages with the appropriate [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) prefix, e.g. `fix:`.

@Mdleal I'm glad you were able to figure it out. I'll update the article with a mention of the `extraManifests` for the Gateway API CRDs in this fix. I do "reinstall" Cilium after the bootstrap since it's being synced by Argo CD. This process is (poorly) documented in [k8s/README.md](https://github.com/vehagn/homelab/blob/6cb4f9966efa0e02eea3e6a9b88877d629c975a5/k8s/README.md).

**Comment by mitchross** [comment]
would this PR / Issue explain why all my apps have 

"upstream connect error or disconnect/reset before headers. reset reason: connection timeout"

when I try to reach them? The best data ive found is that a cert is bad...

**Comment by vehagn** [comment]
@mitchross I don't think so.

Are you trying to use the Gateway API? I think I've seen that error message from there before, though it sounds very generic.
[Cilium 1.16](https://github.com/cilium/cilium/releases/tag/v1.16.0) changed the Envoy containers to standalone, this means that if you want to use privileged ports, e.g. 80 and 443, you need to give Envoy the correct privileges ([docs](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#bind-to-privileged-port)), you can see my config for this [here](https://github.com/vehagn/homelab/blob/300f31629193539d870765d77d60a8ab5f25768c/k8s/infra/network/cilium/values.yaml#L66-L70) and [here](https://blog.stonegarden.dev/articles/2023/12/cilium-gateway-api/#cilium-1).

```yaml
gatewayAPI:
  enabled: true
## Uncomment to run on the host network, e.g. when LoadBalancer Services are not available
#  hostNetwork:
#    enabled: true
envoy:
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
        - NET_ADMIN
        - PERFMON
        - BPF
  ## Enable SYS_ADMIN capability instead of PERFMON and BPF if running on Linux Kernel < 5.8 and Cri-O < 1.22.0 or containerd < 1.5.0
  #       - SYS_ADMIN
  ## Enable NET_BIND_SERVICE capability to use port numbers < 1024, e.g. 80 or 443
  #       - NET_BIND_SERVICE
```

Edit: I see I've not added the `NET_BIND_SERVICE` capability in my config, but I'm still somehow able to use port 443.
Maybe it has something to do with `BPF` + `keepCapNetBindService: true`?

This should definitely work though:

```yaml
gatewayAPI:
  enabled: true
envoy:
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy: [ NET_ADMIN, SYS_ADMIN, NET_BIND_SERVICE ]
```

**Comment by mitchross** [comment]
> @mitchross I don't think so.
> 
> Are you trying to use the Gateway API? I think I've seen that error message from there before, though it sounds very generic. [Cilium 1.16](https://github.com/cilium/cilium/releases/tag/v1.16.0) changed the Envoy containers to standalone, this means that if you want to use privileged ports, e.g. 80 and 443, you need to give Envoy the correct privileges ([docs](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#bind-to-privileged-port)), you can see my config for this [here](https://github.com/vehagn/homelab/blob/300f31629193539d870765d77d60a8ab5f25768c/k8s/infra/network/cilium/values.yaml#L66-L70) and [here](https://blog.stonegarden.dev/articles/2023/12/cilium-gateway-api/#cilium-1).
> 
> ```yaml
> gatewayAPI:
>   enabled: true
> ## Uncomment to run on the host network, e.g. when LoadBalancer Services are not available
> #  hostNetwork:
> #    enabled: true
> envoy:
>   securityContext:
>     capabilities:
>       keepCapNetBindService: true
>       envoy:
>         - NET_ADMIN
>         - PERFMON
>         - BPF
>   ## Enable SYS_ADMIN capability instead of PERFMON and BPF if running on Linux Kernel < 5.8 and Cri-O < 1.22.0 or containerd < 1.5.0
>   #       - SYS_ADMIN
>   ## Enable NET_BIND_SERVICE capability to use port numbers < 1024, e.g. 80 or 443
>   #       - NET_BIND_SERVICE
> ```
> 
> Edit: I see I've not added the `NET_BIND_SERVICE` capability in my config, but I'm still somehow able to use port 443. Maybe it has something to do with `BPF` + `keepCapNetBindService: true`?
> 
> This should definitely work though:
> 
> ```yaml
> gatewayAPI:
>   enabled: true
> envoy:
>   securityContext:
>     capabilities:
>       keepCapNetBindService: true
>       envoy: [ NET_ADMIN, SYS_ADMIN, NET_BIND_SERVICE ]
> ```

Yea I basically have a 1:1 clone of your repo ( minus terraform, automation, but the k8s )

and ive had it all working multiple times.. then one day I got the err, connection reset message and I have been chasing it for weeks. When I redeployed/deleted/messed with cert manager I got it working for a bit... 

The closest issues i found 

https://github.com/cilium/cilium/issues/24146
https://github.com/cert-manager/cert-manager/issues/6799

Im going to nuke my cluster and start over...  see if its a order of operations issue

**Comment by vehagn** [comment]
@luminosita Do you mind if I try to fix the conflicts and merge this?

**Comment by luminosita** [comment]
Sure, absolutely

**Comment by vehagn** [comment]
Did a manual merge to main. Thank you for the contribution!

**Pull request closed without merging**
